services:
  db:
    image: mysql:8.0
    container_name: anastasia_slasie_mysql_db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: SariFeqrey@16
      MYSQL_DATABASE: anastasia_slasie
    ports:
      # CRITICAL: Map the container's 3306 port to a port on your local machine
      - "3306:3306" 
    volumes:
      # Persist the data so it doesn't disappear when you stop the container
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
